### ISSUE TITLE
Missing documentation on several functions

### ISSUE THREAD

**Issue by pablo-chulilla** [MK8BK/ldd2048s1#11]
Writing it right now, will update it tomorrow.

**Comment by MK8BK** [comment]
"missing documentation on several functions" --> "most of them" :);)

**Comment by pablo-chulilla** [comment]
/** génère aléatoirement un 2 ou un 4 avec des probabilités respectives de 9/10 et 1/10
 *  @return 2 ou 4
 *  testée
 **/ 
int tireDeuxOuQuatre(){
	vector<int> fillerValues = {2,2,2,2,4,2,2,2,2,2};
	int index = rand() % 10;
	return fillerValues[index];
}

/** génère un Plateau de dimensions 4*4 ne contenant que des 0
 *  @return un Plateau vide
 *  testée
 **/
Plateau plateauVide(){
	Plateau pvide;
	pvide = Plateau(4);
	for(int i=0; i<4; i++){
		pvide[i] = vector<int>(4);
	}
	return pvide;
}

/** Ajoute une nouvelle tuile de 2 ou de 4 à un plateau
 *  @param Plateau plateau
 *  @return Plateau copy copie de plateau avec une nouvelle tuile de 2 où de 4 à une position aléatoire
 *  testée
*/
Plateau nouvelleTuile(Plateau plateau){
	int v = tireDeuxOuQuatre();
	int i = rand() % 4;
	int j = rand() % 4;
	Plateau copy = plateau;
	while (copy[i][j]!=0){
		i = rand() % 4;
		j = rand() % 4;
	}
	copy[i][j]=v;
	return copy;
}


/** génère deux nombres sur des cases aléatoires d'un Plateau vide
 *  @return un Plateau en début de jeu
 *  testée
 **/
Plateau plateauInitial(){
	Plateau plateau = nouvelleTuile(nouvelleTuile(plateauVide()));
	return plateau;
}

/** tourne un plateau 90 degrés vers la gauche
 *  @param Plateau plateau
 *  @return flippedPlateau plateau tourné 90 degrés vers la gauche
 *  testée
*/
Plateau flippe90TrigPlus(Plateau plateau){
	Plateau flippedPlateau = plateauVide();
	for(int row=0; row<4;row++){
		for(int column=0; column<4; column++){
			flippedPlateau[row][column]=plateau[column][3-row];
		}
	}
	return flippedPlateau;
}


/** déplace les tuiles d'un Plateau vers la gauche et les combine si possible
 *  @param plateau le Plateau
 *  @return le Plateau une fois déplacé vers la gauche
 *  testée
 **/
vector<int> collapseRowLeft(vector<int> row){
	vector<int> nrow = vector<int>(4);
	int count=0;
	for (int column=0; column<4; column++){
			if(row[column]!=0){
				nrow[count]=row[column];
				count++;
			}
			else{
				continue;
				// count++;
			}
	}
	return nrow;
}

/** fusionne les tuiles consécutives de même valeur vers la gauche
 *  @param vector<int> row ligne d'un plateau
 *  @return vector<int> nrow row avec les valeurs consécutives fusionnées vers la gauche
 *  testée
*/
vector<int> mergeRowLeft(vector<int> row){
	vector<int> nrow = vector<int>(4);
	int count=0;
	for (int column=0; column<4; column++){
		if (column!=3 && row[column]==row[column+1]){
			nrow[count]=row[count]*2;
			column++;
			count++;
		}
		else{
			nrow[count]=row[column];
		}
		count++;
	}
	return nrow;
}

/** deplacement vers la gauche selon les regles du jeu
 *  @param Plateau plateau avant le déplacement
 *  @return Plateau shiftGauchePlateau après le déplacement
 *  testée
*/
Plateau deplacementGauche(Plateau plateau){
	Plateau shiftGauchePlateau=plateauVide();
	//combine elements when possible
	for(int row=0; row<4; row++){
		shiftGauchePlateau[row]=collapseRowLeft(mergeRowLeft(collapseRowLeft(plateau[row])));
	}
	return shiftGauchePlateau;
}


/** déplace les tuiles d'un Plateau vers la droite et les combine si possible
 *  @param plateau le Plateau
 *  @return le Plateau une fois déplacé vers la droite
 *  testée
 **/
Plateau deplacementDroite(Plateau plateau){
	//combine elements when possible
	return flippe90TrigPlus(flippe90TrigPlus(deplacementGauche(flippe90TrigPlus(flippe90TrigPlus(plateau)))));
}


/** déplace les tuiles d'un Plateau vers le haut et les combine si possible
 *  @param plateau le Plateau
 *  @return le Plateau une fois déplacé vers le haut
 *  testée
 **/
Plateau deplacementHaut(Plateau plateau){
	//combine elements when possible
	return flippe90TrigPlus(flippe90TrigPlus(flippe90TrigPlus(deplacementGauche(flippe90TrigPlus(plateau)))));
}


/** déplace les tuiles d'un Plateau vers le bas et les combine si possible
 *  @param plateau le Plateau
 *  @return le Plateau une fois déplacé vers le bas
 *  testée
 **/
Plateau deplacementBas(Plateau plateau){
	//combine elements when possible
	return flippe90TrigPlus(flippe90TrigPlus(flippe90TrigPlus(deplacementDroite(flippe90TrigPlus(plateau)))));
}





/** déplace les tuiles d'un Plateau dans la direction donnée et génère une nouvelle tuile si le déplacement est valide
 *  @param plateau le Plateau
 *  @param direction la direction 0 droite 1 Haut 2 Gauche 3 Bas
 *  @return le Plateau déplacé dans la direction
 **/
Plateau deplacement(Plateau plateau, int direction, bool tuile){
	Plateau auxPlateau;
	switch (direction){
		case 0:
			auxPlateau = deplacementDroite(plateau);
			break;
		case 1:
			auxPlateau = deplacementHaut(plateau);
			break;
		case 2:
			auxPlateau = deplacementGauche(plateau);
			break;
		case 3:
			auxPlateau = deplacementBas(plateau);
			break;
	}
	if (auxPlateau==plateau){
		throw invalid_argument("Mouvement Invalide!");
	}
	else{
		if(tuile){
		return nouvelleTuile(auxPlateau);
		}
		else{
			return auxPlateau;
		}
	}
}


/** affiche un Plateau
 *  @param p le Plateau
 *  @return string aDessiner chaine de caractères contenant le plateau à afficher
 *  testée
 **/
string dessine(Plateau p){
	string aDessiner = 	"\n*****************************\n*";
	for(int i=0; i<4; i++){
		for(int j=0; j<4; j++){
			if (p[i][j]==0){
				aDessiner += "      *";
			}
			else if(p[i][j]<10){
				aDessiner += "  "+ to_string(p[i][j]) + "   *";
			}
			else if(p[i][j]<100){
				aDessiner += "  " + to_string(p[i][j]) + "  *";
			}
			else if(p[i][j]<1000){
				aDessiner += " " + to_string(p[i][j]) + "  *";
			}
			else if (p[i][j]<10000){
				aDessiner += " " + to_string(p[i][j]) + " *";
			}
			else if (p[i][j]<100000){
				aDessiner += "" + to_string(p[i][j]) + " *";
			}
			else{
				aDessiner += "" + to_string(p[i][j]) + "*";
			}
		}
		if (i!=3){
			aDessiner += "\n*****************************\n*";
		}else{
			aDessiner += "\n*****************************\n";
		}
	}
	return aDessiner;
}


/** permet de savoir si une partie est terminée
 *  @param plateau un Plateau
 *  @return true si le plateau est vide, false sinon
 *  testée
 **/
bool estPerdant(Plateau plateau){
	Plateau p = plateau;
	if(deplacementDroite(p)==p && deplacementHaut(p)==p && deplacementGauche(p)==p && deplacementBas(p)==p){
		return true;
	}
	return false;
}


/** permet de savoir si une partie est gagnée
 * @param plateau un Plateau
 * @return true si le plateau contient un 2048, false sinon
 * testée
 **/
bool estGagnant(Plateau plateau){
	for(int row=0; row<4; row++){
		for(int column=0; column<4; column++){
			if(plateau[row][column]==2048){
				return true;
			}
		}
	}
	return false;
}






//earlier implementation
//half-done, continue after emergency git versions management (concerning this function)
//int score(int score_avant, Plateau avant, int ideplacement){
//	Plateau apres;
//	apres = deplacement(avant, ideplacement, false);
//	int nscore=score_avant;
//	vector<vector<int>> avant_freq= {{2,4,8,16,32,64,128,256,512,1024,2048,4096,8192,16384,32768,65536,131072},
//	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
//	vector<vector<int>> apres_freq= avant_freq;
//	for(int column=0; column<17; column++){
//		avant_freq[1][column]=count(avant, avant_freq[0][column]);
//		apres_freq[1][column]=count(apres, apres_freq[0][column]);
//		if(apres_freq[1][column]>avant_freq[1][column]){
//			nscore += avant_freq[0][column]*(apres_freq[1][column]-avant_freq[1][column]);
//		}
//	}
//	return nscore;
//}

//new proposed implementation by @pablo-chulilla
//still debating logic regarding the score incrementation


/** Calcule le score correspondant à un plateau en fonction du plateau avant le déplacement, la direction du deplacement et le score 
 *  précédent
 *  @param int score_avant, le score antérieur
 *  @param Plateau avant, le plateau avant le déplacement
 *  @param int ideplacement
 *  @return int nscore le score
 *  testée
*/
int score(int score_avant, Plateau avant, int ideplacement){
	Plateau apres;
	apres = deplacement(avant, ideplacement, false);
	int nscore=score_avant;
	vector<vector<int>> avant_freq= {{2,4,8,16,32,64,128,256,512,1024,2048,4096,8192,16384,32768,65536,131072},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
	vector<vector<int>> apres_freq= avant_freq;
	for(int column=0; column<17; column++){
		avant_freq[1][column]=count(avant, avant_freq[0][column]);
		apres_freq[1][column]=count(apres, apres_freq[0][column]);
	}
	for(int column=0; column<17; column++){
		if(apres_freq[1][column]>avant_freq[1][column]){
			nscore += avant_freq[0][column]*(apres_freq[1][column]-avant_freq[1][column]);
		}
		if(apres_freq[1][column]<avant_freq[1][column] and apres_freq[1][column + 1]==avant_freq[1][column + 1]){
			nscore = nscore + avant_freq[0][column]*(avant_freq[1][column]-apres_freq[1][column]);
		}
	}
	return nscore;
}



/*  demande un char à l'utilisateur
 *  @return char output
 */
char input_dhgb(){
	// cin.ignore(12000,'\n');
	string input;
	cout<<"Entrer commande:";
	getline(cin, input);
	if(input.length()!=1){
		throw invalid_argument("Deplacement non-autorise!");
	}
	char output = input[0];
	output = toupper(output);
	if(output!='D' && output!='H' && output!='G' && output!='B' && output!='Q'){
		throw invalid_argument("Deplacement non-autorise!");
	}
	return output;

	// char output = input[0];
	// output = toupper(output);
		
	// return output;
}


/* assigne un entier compris entre -1 et 3 à un char
 * @param char dhgb d, h, g, b ou q
 * @return int -1, 0, 1, 2, ou 3
 */
int ideplacement_dhgb(char dhgb){
	switch (dhgb){
		case 'D':
			return 0;
			break;
		case 'H':
			return 1;
			break;
		case 'G':
			return 2;
			break;
		case 'B':
			return 3;
			break;
		case 'Q':
			return -1;
			break;
		default:
			throw invalid_argument("if this appears, run!");
		}
}

//testée en modifiant estGagnant pour ne pas devoir arriver à 2048 pour passer par les différentes parties du programme. 
void jeu(){
	srand((unsigned) time(0));
	int game_score = 0;
	Plateau plateau = plateauInitial();
	Plateau plateau_next = plateauVide();
	bool jeuGagne = false;
	while(true){
        initscr();
		cout << dessine(plateau)<< endl << "score:" <<game_score<<endl;
		try{
			int deplacement_id = ideplacement_dhgb(input_dhgb());
			if(deplacement_id==-1){
				cout << "Jeu terminee" << endl;
				return;
			}
			plateau_next = deplacement(plateau, deplacement_id, true);
			game_score = score(game_score, plateau, deplacement_id);
			plateau = plateau_next;
			if(estGagnant(plateau) && jeuGagne==false){
				cout << dessine(plateau_next) << endl;
				jeuGagne = true;
				cout << "Vous avez Gagne!\nVoulez vous continuer a jouer?(Y/N):";
				string choice;
				getline(cin, choice);
				if(choice=="N"){
					return;
				}
			}else if(estPerdant(plateau)){
				cout << dessine(plateau_next) << endl;
				cout << "Vous avez Perdu!"<<endl;
				return;
			}
		}catch(invalid_argument e){
			cout << endl << e.what() << endl;
			continue;
		}
        endwin();
	}
}
