### ISSUE TITLE
ncurses arrow moves 

### ISSUE THREAD

**Issue by pablo-chulilla** [MK8BK/ldd2048s1#15]
the new jeu() function

**Comment by pablo-chulilla** [comment]
void jeu(){
	initscr();
	refresh();
	cbreak();
	noecho();
	keypad(stdscr,true);
	srand((unsigned) time(0));

	char vide = ' ';
	int xMax, yMax;
	getmaxyx(stdscr, yMax, xMax);
	WINDOW * board_win = newwin(11, 31, (yMax/2) - 7, (xMax/2) - 16);
	refresh();

	int game_score = 0;
	Plateau plateau = plateauInitial();
	Plateau plateau_next = plateauVide();
	bool jeuGagne = false;
	while(true){		
		refresh();
		mvwprintw(board_win, 0, 0, "-----------------------------\n-      -      -      -      -\n-----------------------------\n-      -      -      -      -\n-----------------------------\n-      -      -      -      -\n-----------------------------\n-      -      -      -      -\n-----------------------------\n-----------------------------");
		wrefresh(board_win);
		mvwprintw(board_win, 0, 0, dessine(plateau).data());
		wrefresh(board_win);
		//dessine(plateau);
		//cout << endl; 
		//cout << "score:" <<game_score<<endl;

		//cout << dessine(plateau)<< endl << "score:" <<game_score<<endl;
		try{
			//int deplacement_id = ideplacement_dhgb(input_dhgb());
			int deplacement_id = get_input_arrows();
			if(deplacement_id==-1){
				cout << "Jeu termine" << endl;
				return;
			}
			plateau_next = deplacement(plateau, deplacement_id, true);
			game_score = score(game_score, plateau, deplacement_id);
			plateau = plateau_next;
			if(estGagnant(plateau) && jeuGagne==false){		
				mvwprintw(board_win, 0, 0, dessine(plateau_next).data());
				wrefresh(board_win);
				//dessine(plateau_next);
				//cout << endl; 

				//cout << dessine(plateau_next) << endl;
				jeuGagne = true;
				cout << "Vous avez Gagne!\nVoulez vous continuer a jouer?(Y/N):";
				string choice;
				getline(cin, choice);
				if(choice=="N"){
					return;
				}
			}else if(estPerdant(plateau)){
				mvwprintw(board_win, 0, 0, dessine(plateau_next).data());
				wrefresh(board_win);
				//dessine(plateau_next);
				//cout << endl; 

				//cout << dessine(plateau_next) << endl;
				cout << "Vous avez Perdu!"<<endl;
				return;
			}
			system("clear");
		}catch(invalid_argument e){
			system("clear");
			cout << endl << e.what() << endl;
			continue;
		}
	}
	endwin();
}

**Comment by MK8BK** [comment]
find a way to remove ^D ^H when arrow keys hit, otherwise perfect 👍

**Comment by MK8BK** [comment]
also terminal doesnt display typed input afterwards, weird behaviour after execution

**Comment by MK8BK** [comment]
also, if input different than arrow keys, shoul

**Comment by pablo-chulilla** [comment]
//I have modified jeu() and get_input_arrows(), also now the game ends when supr is typed
int get_input_arrows(){
	int c;
	// newterm(NULL, stdin, stdout);
	// keypad(stdscr, true);
	//addch(c);
	// ;
	int answer = -2;
	while (answer == -2){
		c = getch();
		if(c==KEY_RIGHT){
			answer=0;
		}else if(c==KEY_UP){
			answer =1;
		}else if(c==KEY_LEFT){
			answer=2;
		}else if(c==KEY_DOWN){
			answer=3;
		}else if(c==KEY_DC){
			answer=-1;
		}else{
			answer=-2;
		}
	}
	return answer;
}

void jeu(){
	initscr();
	refresh();
	cbreak();
	noecho();
	keypad(stdscr,true);
	srand((unsigned) time(0));

	char vide = ' ';
	int xMax, yMax;
	getmaxyx(stdscr, yMax, xMax);
	WINDOW * board_win = newwin(11, 31, (yMax/2) - 7, (xMax/2) - 16);
	refresh();

	int game_score = 0;
	Plateau plateau = plateauInitial();
	Plateau plateau_next = plateauVide();
	bool jeuGagne = false;
	while(true){		
		refresh();
		mvwprintw(board_win, 0, 0, "-----------------------------\n-      -      -      -      -\n-----------------------------\n-      -      -      -      -\n-----------------------------\n-      -      -      -      -\n-----------------------------\n-      -      -      -      -\n-----------------------------\n-----------------------------");
		wrefresh(board_win);
		mvwprintw(board_win, 0, 0, dessine(plateau).data());
		wrefresh(board_win);
		cout << "score :" << game_score << endl;
		//dessine(plateau);
		//cout << endl; 
		//cout << "score:" <<game_score<<endl;

		//cout << dessine(plateau)<< endl << "score:" <<game_score<<endl;
		try{
			//int deplacement_id = ideplacement_dhgb(input_dhgb());
			int deplacement_id = get_input_arrows();
			if(deplacement_id==-1){
				cout << "Jeu termine" << endl;
				system("stty sane");
				return;
			}
			plateau_next = deplacement(plateau, deplacement_id, true);
			game_score = score(game_score, plateau, deplacement_id);
			plateau = plateau_next;
			if(estGagnant(plateau) && jeuGagne==false){		
				mvwprintw(board_win, 0, 0, dessine(plateau_next).data());
				wrefresh(board_win);
				//dessine(plateau_next);
				//cout << endl; 

				//cout << dessine(plateau_next) << endl;
				jeuGagne = true;
				cout << "Vous avez Gagne!\nVoulez vous continuer a jouer?(Y/N):";
				string choice;
				getline(cin, choice);
				if(choice=="N"){
					system("stty sane");
					return;
				}
			}else if(estPerdant(plateau)){
				mvwprintw(board_win, 0, 0, dessine(plateau_next).data());
				wrefresh(board_win);
				//dessine(plateau_next);
				//cout << endl; 

				//cout << dessine(plateau_next) << endl;
				cout << "Vous avez Perdu!"<<endl;
				system("stty sane");
				return;
			}
			system("clear");
		}catch(invalid_argument e){
			system("clear");
			cout << endl << e.what() << endl;
			continue;
		}
	}
	endwin();
	system("stty sane");
}
