### ISSUE TITLE
Game stops when 2048 is reached and weird display when string input starts with dghb and contains more than 1 char

### ISSUE THREAD

**Issue by pablo-chulilla** [MK8BK/ldd2048s1#7]
jeu() works properly until 2048 is reached,  "Vous avez Gagné!" is then displayed and then the game stops, return in if(estGagnant(plateau) must be removed and a bool variable must be added to contain the information on wether the game has previously been won or not(tested it by changing estGagne() to consider that the game is won when a smaller value is reached, it works). FIXED
Also when a string input such as dh begins with dghb it is accepted, the movement is made but plateau isn't properly drawn, input_dhgb()'s condition has to be changed. NOT FIXED
Maybe adding "Q" condition to input_dhgb() and ideplacement_dhgb() to finish the game in addition to it ending when estTermine(plateau) is true might be a good idea. ADDED

**Comment by MK8BK** [comment]
managed to handle incorrect user input and added Q
did your implementation of estGagnat() work properly?
if so we'll merge the code this afternoon

**Comment by pablo-chulilla** [comment]
Changes have been implemented for jeu(), also quitting after winning option has been added.
